.PHONY: clean All

All:
	@echo "----------Building project:[ NEW8210Project - Release ]----------"
	@cd "NEW8210Project" && "$(MAKE)" -f  "NEW8210Project.mk"
clean:
	@echo "----------Cleaning project:[ NEW8210Project - Release ]----------"
	@cd "NEW8210Project" && "$(MAKE)" -f  "NEW8210Project.mk" clean
